# LLM 摘要生成 API 配置
llm_chat:
  api_base_url: "https://uni-api.cstcloud.cn/v1"
  api_key: "af5f27d7e97362692b7b64f69c9a12ef4995a5742df75c0da2cfcfe1c0f8de91"
  model_name: "qwen3:235b"

# Embedding 模型配置
embedding:
  model: "qwen3-embedding:8b"
  api_key: "e6ec0cfa15e53ad712070ec3e6bbfa2ff59976ccc312fffc77ade4b4069111a6"
  base_url: "https://uni-api.cstcloud.cn/v1"  